
info:
  contact: {}
  description: This is an Order Api just for young people
  termsOfService: http://swagger.io/terms/
  title: Order Api
  version: "1.0"
tags:
 - name: rol
    description: Operations about Orders
schemes:
  - http

paths:
    
  /rol:
    get:
    
      rols:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Getting Order by Code
      tags:
      - Orders
swagger: "2.0"